{{- if and .Values.consumer.enabled .Values.consumer.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumer-ingress
  namespace: {{ .Values.consumer.namespace }}
  labels:
    {{- include "apigw-poc.consumer.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.global.tls.clusterIssuer | quote }}
    {{- end }}
    {{- with .Values.consumer.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.consumer.ingress.className }}
  {{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - consumer.{{ .Values.global.domainSuffix }}
    secretName: consumer-tls-cert
  {{- end }}
  rules:
  - host: consumer.{{ .Values.global.domainSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: consumer-service
            port:
              number: {{ .Values.consumer.service.port }}
{{- end }}
