{{- if .Values.consumer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Values.consumer.namespace }}
  labels:
    {{- include "apigw-poc.consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
      - name: {{ .Values.consumer.name }}
        image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
        imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.consumer.service.targetPort }}
          name: http
        env:
        - name: PORT
          value: {{ .Values.consumer.env.PORT | quote }}
        - name: PRODUCER_API_URL
          value: {{ .Values.consumer.env.PRODUCER_API_URL | quote }}
        {{- with .Values.consumer.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.consumer.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.consumer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
