{{- if eq (include "apigw-poc.kong.keycloak.enabledReady" .) "true" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-oauth2-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apigw-poc.kong.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kong.keycloakAuth.oauth2Proxy.replicaCount }}
  selector:
    matchLabels:
      app: kong-oauth2-proxy
  template:
    metadata:
      labels:
        app: kong-oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: "{{ .Values.kong.keycloakAuth.oauth2Proxy.image.repository }}:{{ .Values.kong.keycloakAuth.oauth2Proxy.image.tag }}"
        imagePullPolicy: {{ .Values.kong.keycloakAuth.oauth2Proxy.image.pullPolicy }}
        args:
        - --http-address=0.0.0.0:4180
        - --provider=oidc
        - --oidc-issuer-url={{ include "apigw-poc.kong.keycloak.issuerUrl" . }}
        - --client-id={{ .Values.kong.keycloakAuth.clientId }}
        - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
        - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
        - --scope=openid profile email
        - --reverse-proxy=true
        - --upstream=static://200
        - --skip-provider-button=true
        - --set-xauthrequest=true
        - --cookie-secure=true
        - --cookie-domain={{ default (printf ".%s" .Values.global.domainSuffix) .Values.kong.keycloakAuth.cookieDomain }}
        - --whitelist-domain={{ default (printf ".%s" .Values.global.domainSuffix) .Values.kong.keycloakAuth.cookieDomain }}
        {{- range .Values.kong.keycloakAuth.emailDomains }}
        - --email-domain={{ . }}
        {{- end }}
        {{- range .Values.kong.keycloakAuth.extraArgs }}
        - {{ . | quote }}
        {{- end }}
        env:
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kong-oauth2-proxy
              key: client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: kong-oauth2-proxy
              key: cookie_secret
        ports:
        - name: http
          containerPort: 4180
          protocol: TCP
        {{- with .Values.kong.keycloakAuth.oauth2Proxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}

