{{- if .Values.kong.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: {{ .Values.kong.namespace }}
  labels:
    {{- include "apigw-poc.kong.labels" . | nindent 4 }}
data:
  kong.yml: |
    {{- .Values.kong.config | toYaml | nindent 4 }}
{{- end }}
