{{- if and .Values.kong.enabled .Values.kong.managerIngress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-manager-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apigw-poc.kong.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.global.tls.clusterIssuer | quote }}
    {{- end }}
    {{- if eq (include "apigw-poc.kong.keycloak.enabledReady" .) "true" }}
    traefik.ingress.kubernetes.io/router.middlewares: "kong-manager-auth@kubernetescrd"
    {{- end }}
    {{- with .Values.kong.managerIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.kong.managerIngress.className }}
  {{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - kong-admin.{{ .Values.global.domainSuffix }}
    secretName: kong-manager-tls-cert
  {{- end }}
  rules:
  - host: kong-admin.{{ .Values.global.domainSuffix }}
    http:
      paths:
      {{- if eq (include "apigw-poc.kong.keycloak.enabledReady" .) "true" }}
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: kong-oauth2-proxy
            port:
              number: 4180
      {{- end }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-proxy
            port:
              number: {{ .Values.kong.service.ports.manager }}
{{- end }}

