{{- if and .Values.producer.enabled .Values.producer.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: producer-ingress
  namespace: {{ .Values.producer.namespace }}
  labels:
    {{- include "apigw-poc.producer.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.global.tls.clusterIssuer | quote }}
    {{- end }}
    {{- with .Values.producer.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.producer.ingress.className }}
  {{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - producer.{{ .Values.global.domainSuffix }}
    secretName: producer-tls-cert
  {{- end }}
  rules:
  - host: producer.{{ .Values.global.domainSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: producer-service
            port:
              number: {{ .Values.producer.service.port }}
{{- end }}
