{{- if .Values.producer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.producer.name }}
  namespace: {{ .Values.producer.namespace }}
  labels:
    {{- include "apigw-poc.producer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.producer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.producer.name }}
    spec:
      containers:
      - name: {{ .Values.producer.name }}
        image: "{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
        imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.producer.service.targetPort }}
          name: http
        env:
        - name: PORT
          value: {{ .Values.producer.env.PORT | quote }}
        {{- with .Values.producer.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.producer.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.producer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
